name: Create Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Create extension ZIP
      run: |
        zip -r pocketcasts-search-extension-${{ github.ref_name }}.zip . \
          -x "*.git*" \
          -x ".github/*" \
          -x "node_modules/*" \
          -x "package*.json" \
          -x ".prettierrc" \
          -x "*.zip" \
          -x "README.md"

    - name: Create Release
      run: |
        gh release create ${{ github.ref_name }} \
          --title "Release ${{ github.ref_name }}" \
          --notes "Chrome extension release ${{ github.ref_name }}

        Download the ZIP file and upload it to the Chrome Web Store." \
          pocketcasts-search-extension-${{ github.ref_name }}.zip
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}